In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
l=[2,3,4,5,6,"hello"]
l


[2, 3, 4, 5, 6, 'hello']

In [9]:
arr=np.array([l])
arr

array([['2', '3', '4', '5', '6', 'hello']], dtype='<U21')

2d Array

In [10]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [23]:
arr=np.zeros(6,int)
arr

array([0, 0, 0, 0, 0, 0])

In [24]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [26]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [33]:
arr=np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
import os
os.getcwd()


'C:\\Users\\com'