In [1]:
import numpy as np

# numpy indexing and slicing of vectors

In [2]:
arr=np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[2:5]

array([12, 13, 14])

In [4]:
arr[:7]

array([10, 11, 12, 13, 14, 15, 16])

In [5]:
arr[4:]

array([14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[1:8:2]

array([11, 13, 15, 17])

In [8]:
arr[3]

np.int64(13)

In [15]:
arr=np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [17]:
arr[0,0]

np.int64(1)

In [18]:
arr[0,4]

np.int64(5)

# 2d slicing 

In [21]:
  arr[1:3,1:3]       # array[  row start: row end+1  ,   col start : col end+1  ]

array([[ 7,  8],
       [12, 13]])

In [22]:
arr[2:4,3:5]

array([[14, 15],
       [19, 20]])

# only coluumn

In [23]:
arr[:,2]

array([ 3,  8, 13, 18])