In [1]:
import numpy as np

In [23]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [24]:
# summation of each row 
sr=np.sum(s,axis=1)
sr

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [25]:
sr[ : : ]==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [26]:
# summation of each column
sc=np.sum(s,axis=0)
sc

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [27]:
#total sum
a=s.sum()
a

np.int64(405)

In [28]:
#is each column sum is equal 45
b=sc[: : ]==45
for i in b:
    if i==0:
        print("suduko is not valid")
        break 
        
else:
        print("sudoko is correct")

sudoko is correct


In [29]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [31]:
#slicing first square
s1=s[ :3, :3]
s1

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [33]:
s1.sum()

np.int64(45)

In [34]:
s2=s[:3,3:6]
s2

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [37]:
s9=s[6:,6:]
s9

array([[2, 8, 4],
       [6, 3, 5],
       [1, 7, 9]])

In [39]:
len(s)

9

In [44]:
#each square print using loop
for i in range( 0,len(s),3):
    for j in range(0,len(s),3):
        print(s[i:i+3,j:j+3])
    

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [49]:
#each square sum = 45
for i in range( 0,len(s),3):
    for j in range(0,len(s),3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45
