In [2]:
import numpy as np

# Array attributes

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.shape

(3, 3)

In [7]:
arr.size

9

In [8]:
arr.dtype

dtype('int64')

# Array methods

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr.min()

np.int64(1)

In [13]:
arr.max()

np.int64(9)

In [14]:
arr.sum()

np.int64(45)

In [26]:
np.sum(arr,axis=0)            #column er sum where axis=0

array([12, 15, 18])

In [28]:
np.sum(arr,axis=1)            #Row er sum where axis=1

array([ 6, 15, 24])

In [17]:
arr.mean()

np.float64(5.0)

In [18]:
arr.std()

np.float64(2.581988897471611)

In [23]:
a=arr.argmax()
a

np.int64(8)

In [24]:
arr.argmin()

np.int64(0)

# Reshape

In [29]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [30]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])