In [1]:
import numpy as np


In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1


array([1, 2, 3, 4, 5])

In [5]:
sum1=a1+a2
sum1

array([ 7,  9, 11, 13, 15])

In [7]:
sub1=a2-a1
sub1

array([5, 5, 5, 5, 5])

In [11]:
a2/a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [12]:
a2//a1

array([6, 3, 2, 2, 2])

In [13]:
a2**a1

array([     6,     49,    512,   6561, 100000])

In [15]:
a1

array([1, 2, 3, 4, 5])

In [16]:
 a1+10

array([11, 12, 13, 14, 15])

# deep copy and shallow  copy

In [17]:
a=np.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [19]:
slice=a[:5]
slice=slice+10
slice

array([11, 12, 13, 14, 15])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [21]:
a[4:7]*5

array([25, 30, 35])

In [22]:
a[:5:2]

array([1, 3, 5])

In [27]:
b=a           #deep copy 
b[0]=90
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [28]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [29]:
c=a.copy()  #shallow copy
c[0]=17
c

array([17,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [30]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

# Matrix multiplication

In [32]:
mat_1=np.arange(1,7).reshape(3,2)
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
mat_2=np.arange(2,6).reshape(2,2)
mat_2

array([[2, 3],
       [4, 5]])

In [36]:
mat_1@mat_2    # matrix multiplication = @

array([[10, 13],
       [22, 29],
       [34, 45]])

In [38]:
np.dot(mat_1,mat_2) # dot matrix multiplication

array([[10, 13],
       [22, 29],
       [34, 45]])

In [39]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
mat_1.T   # transpose

array([[1, 3, 5],
       [2, 4, 6]])

# stacking 

In [43]:
# horizental
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [44]:
#vertical
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
# cloumn stack
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

# split

In [46]:
c=np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
#horizontal split
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [48]:
#vertical split
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]