In [1]:
import numpy as np


In [4]:
#linspace(intial,last,how many num want)
arr = np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

Random Generation Function

In [9]:
arr=np.random.rand(6)
arr

array([0.63947134, 0.88997254, 0.95163612, 0.76782378, 0.14816822,
       0.70958413])

random with standardization means limit 3 to -3

In [11]:
np.random.randn(10)

array([ 1.21208801,  3.21695749,  0.69622787, -3.56115966, -0.41754497,
       -1.40679453,  0.90660782, -0.46394239, -0.85707447, -0.69465456])

In [14]:
#randint( 0 to limit)
arr=np.random.randint(5)
arr

1

In [15]:
#randint( start,last,how many number)
arr=np.random.randint(10,20,5)
arr

array([11, 16, 10, 14, 15], dtype=int32)